title: Weitai Kang
position: Ph.D. Student
affiliation: Illinois Institute of Technology
email: wkang11 (at) hawk.iit.edu

google_scholar: https://scholar.google.com/citations?user=hDl0MkwAAAAJ&hl=en
linkedin: https://www.linkedin.com/in/%E4%BC%9F%E6%B3%B0-%E5%BA%B7-856961247/

logo: /assets/img/personal2.jpg
description: Personal Website
# show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
